spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/startup_project
    username: postgres
    password: umar2308
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8086

app:
  files:
    baseFolder: /files